# AWS CodeBuild

version: 0.2

env:
  variables:
    HUGO_VERSION: "0.100.1"

phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_Linux-32bit.tar.gz
      - tar -xzf hugo_$HUGO_VERSION_Linux-64bit.tar.gz
      - echo $PATH
  build:
    commands:
      - python3 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint
      - make test
artifacts:
  files:
    - .ebextensions/options.config
    - main.py
    - requirements.txt