# AWS CodeBuild

version: 0.2

env:
  variables:
    HUGO_VERSION: "0.100.1"

phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
  build:
    commands:
      - hugo -D
      - hugo deploy