baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[[deployment.targets]]
name = 'hugo-static-website'
URL = 's3://itsdaveba-hugo-static-website?region=us-east-1'